### ISSUE TITLE
Perhaps using pypher?

### ISSUE THREAD

**Issue by cristianvasquez** [HEmile/semantic-markdown-converter#1]
Hello, 

I'm trying to load the data generated from a small vault but I get a syntax error. I imagine it is because of some strange character in my Vault. 
```
Invalid input ')': expected an identifier character, whitespace or NodeLabel (line 2, column 20 (offset: 53))
"IF NOT EXISTS ON (n) ASSERT n.name IS UNIQUE;"
                    ^
```

Perhaps using something like https://neo4j.com/blog/express-cypher-queries-pure-python-pypher/ to write the Cypher statements would be 'safer'?

**Comment by HEmile** [comment]
Hi, thank you for your report.
> Perhaps using something like https://neo4j.com/blog/express-cypher-queries-pure-python-pypher/ to write the Cypher statements would be 'safer'?
I realized just this morning that this is a much better idea, indeed. That's the next thing for this project, will make it a lot easier to use.

Anyways, you're right with your report. Apparently, these statements are only available in the enterprise edition of Neo4j. No idea how it didn't crash for me... It's fixed (just run `pip install --upgrade semantic-markdown-converter`
