### ISSUE TITLE
Use '~' instead of '-'?

### ISSUE THREAD

**Issue by corode** [HEmile/semantic-markdown-converter#9]
Using ```- relationshipTo [[random page]]``` means that certain things get picked up as relationships which I don't like e.g. a todo in the format ```- [x] [[page of a task]]```.

Thus, it might be better to use something not used for lists/other things in general such as '~' i.e. ```~ relationshipTo [[random page]]``` 

N.B. Your plugin has sold obsidian to me! I think I'm never leaving.

**Comment by HEmile** [comment]
Hi! This is a good idea. It should be easy to make this a setting, but I don't think I'll default it as `- rel [[page]]` renders like a list, which looks nice (but indeed is going to give false positives).

> N.B. Your plugin has sold obsidian to me! I think I'm never leaving.

That's really cool to hear :)

**Comment by corode** [comment]
That makes sense, optional is the way to go!
